### ISSUE TITLE
var app = (0, _deku.tree)((0, _deku.element)(List, { items: items }));

### ISSUE THREAD

**Issue by dschalk** [xeodou/deku-to-do-list#1]
The app won't run. The browser console

 has this underlined:
"var app = (0, _deku.tree)((0, _deku.element)(List, { items: items }));"  with the error message:

"Uncaught TypeError: (0 , _deku.element) is not a function"

The reference is to line 106 of build.js. Here is the screen shot:

(https://cloud.githubusercontent.com/assets/2214003/11456577/82f4f514-965b-11e5-9291-75afd98026d5.png)

**Comment by xeodou** [comment]
it works for me ,  maybe you can give me more information. 
PS: The build command is `npm run build`

**Comment by xeodou** [comment]
And then you run like `python -m SimpleHTTPServer` start a static server.

**Comment by xeodou** [comment]
I add a new command `npm run static` will host the file at the http://127.0.0.1:8080

**Comment by danmakenoise** [comment]
Got here from Google! In case anyone else gets this error, it's because `tree` was removed from Deku after version 1.0. Just specify version 1.0.0 in your package.json and this will still work.

**Comment by xeodou** [comment]
Thanks @danmakenoise , i will update the example to the latest version of deku.

**Comment by xeodou** [comment]
Hi @danmakenoise and @dschalk i just upgrade to the latest version of deku. It works now. If are interesting what changes in these two version, please look at the diff.

**Comment by danmakenoise** [comment]
Awesome, thanks for doing that!
